version: "3.8"

services:
  oracle:
    # Name of the Docker Compose service
    image: gvenzl/oracle-free:23-slim-faststart  # Docker Hub image (can change the tag "latest" to another available version)
    ports:
      - "1521:1521"  # Forward Oracle port to localhost
    environment:
      ORACLE_PASSWORD: sys_user_password  # Password for the SYS user
      APP_USER: my_user                   # Name of the application user
      APP_USER_PASSWORD: password_i_should_change  # Password for the application user
    healthcheck:
      test: ["CMD", "healthcheck.sh"]  # Healthcheck script options
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
      start_interval: 5s

